project:
  type: website
  output-dir: docs


website:
  title: "Lab Book Ising Model"
  sidebar:
    smooth-scroll: true
    logo: img/logo.png
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - intro.ipynb
      - theory.ipynb
      - optimisations.ipynb
      - simulating_im.ipynb
      - finding_tc.ipynb
      - critical_exponents.ipynb
      - discussion.ipynb



format:
  html:
    theme: cosmo
    grid:
      sidebar-width: 305px
    toc: true
    number-chapters: false
    number-sections: false